### ISSUE TITLE
Conflict with Mod List 1.20.1 Forge

### ISSUE THREAD

**Issue by Nathanator9000** [Team-Let-s-Do/DoAPI#12]
I was working on my modpack and noticed it was crashing and tried to isolate it. Unfortunately it seems to be multiple mods together that cause this crash. All these mods work together unless combined at the same time. They all work together unless all six are combined at once. It did not create a crash report, but I copied the log.

Mod List: Let's Do Api 1.2.8, Combat next 1.0.2, Moonlight 2.8.78, Caelus 3.1.0, Architectury 9.1.12, MIAPI 1.1.5

[Launcher Log.txt](https://github.com/Cristelknight999/DoAPI/files/13796002/Launcher.Log.txt)

**Comment by Smartin-b** [comment]
at fault was Combat next, pr is submitted https://github.com/Thelnfamous1/Combat-Next/pull/12

**Comment by Cristelknight999** [comment]
@RedPxnda no. Probably was an accident. But this issue isn't because of DoApi? I'm not home so i can't do anything anyway
