### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Halloween67** [Team-Let-s-Do/DoAPI#13]
Im using Forgified fabric and sinytra connector to simulate forge to fabric and then i have a ton of forge mods, and a couple fabric mods and do api seems to give this error code whenever i use it : 
The game crashed whilst initializing game
Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'doapi'!

how do i fix it xd

**Comment by Cristelknight999** [comment]
Sorry for replying so late. It probably crashed, because do-api has a reforged version of terraform wood api. when a fabric mod also includes the normal terraform wood-api. it will probably cause a crash

**Comment by Cristelknight999** [comment]
that COULD be the problem. but also sinatra is very experimental. so there could be many other things that cause it
