### ISSUE TITLE
[BUG] do api 1.2.9 launch crashes on quilt this is more of an api issue than one of your mods.

### ISSUE THREAD

**Issue by netcore10** [Team-Let-s-Do/DoAPI#15]
### What mod appears to be problematic?

🌲 BloomingNature

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

[crash-2024-03-23_17.14.52-client.txt](https://github.com/Team-Let-s-Do/DoAPI/files/14733048/crash-2024-03-23_17.14.52-client.txt)

### Relevant log output

```shell
https://mclo.gs/tRDKNPf
```

### What modloader are you running the mod on?

Quilt

**Comment by Cristelknight999** [comment]
In the crash doapi is mentioned once (in the mod list) and it seems like it has nothing to do with the crash. It seems to be more related to create.
