### ISSUE TITLE
[BUG] Game crashes with easynpc mod

### ISSUE THREAD

**Issue by SandFoll** [Team-Let-s-Do/DoAPI#17]
### What mod appears to be problematic?

🌲 BloomingNature

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is the mod running in an unstable environment?

- [X] I am using a supported modloader (Forge, Fabric, Quilt)
- [ ] I have self built the mod
- [ ] This is running in a dev environment

### Current Behavior

When I used the costumes in the brewery mod to right-click on the NPC in the easynpc mod, the game crashed. At the same time, the game crashed for all players in the server. The do api was mentioned in the crash log. After the game crashes, if you delete the module and re-enter the game, it will still crash.

### What modloader are you running the mod on?

Forge

**Comment by Cristelknight999** [comment]
Seems to be solved in the dc. Also we should rework the custom armor rendering some time
